[build-system]
requires = ["setuptools>=61.2", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "geetools"
version = "0.6.14"
description = "A collection of tools to work with Google Earth Engine Python API"
keywords = ["python", "geospatial", "remote-sensing", "google-earth-engine", "earthengine"]
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Intended Audience :: Developers",
    "Topic :: Software Development :: Build Tools",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
]
requires-python = ">=3.8"
dependencies = [
    "earthengine-api",
    "requests",
    "pandas",
    "geopandas",
    "deprecated",
    "ee-extra",
]

[[project.authors]]
name = "Rodrigo E. Principe"
email = "fitoprincipe82@gmail.com"

[project.license]
text = "MIT"

[project.readme]
file = "README.md"
content-type = "text/markdown"

[project.urls]
github = "https://github.com/gee-community/gee_tools"

[project.optional-dependencies]
"dev" = [
    "pre-commit",
    "nox",
    "commitizen"
]
"test" = [
    "pytest",
    "pytest-sugar",
    "pytest-cov",
    "pytest-deadfixtures",
    "httplib2",
    "pytest-regressions",
    "Pillow",
]
doc = [
  "sphinx>=6.2.1",
  "pydata-sphinx-theme",
  "sphinx-copybutton",
  "sphinx-design",
  "sphinx-autoapi",
  "ipykernel",
  "httplib2",
  "jupyter-sphinx",
]

[tool.setuptools]
include-package-data = true

[tool.setuptools.packages.find]
include = ["geetools*"]
exclude = ["tests*", "docs*"]

[tool.licensecheck]
using = "PEP631:test;dev;doc"

[tool.ruff]
ignore-init-module-imports = true
fix = true
select = ["E", "F", "W", "I", "D", "RUF"]
extend-exclude = ["geetools/__init__.py"]
force-exclude = true # to make sure exclude is respected when used via pre-commit
ignore = [
  "E501",  # line too long | Black take care of it
  "D213",  # Multi-line docstring | We use D212
]

[tool.ruff.flake8-quotes]
docstring-quotes = "double"

[tool.ruff.pydocstyle]
convention = "google"

[tool.ruff.per-file-ignores]
"tests/*" = ["D102"] # Missing docstring in public method | this is test who cares

[tool.pytest.ini_options]
testpaths = "tests"

[tool.coverage.run]
source = ["geetools"]